### ISSUE TITLE
French Translation

### ISSUE THREAD

**Issue by nels0nwu** [nels0nwu/fuzzy-text#1]

**Comment by nikogrnr** [comment]
[strings.xml.gz](https://github.com/nels0nwu/fuzzy-text/files/6911177/strings.xml.gz)
Please find a french translation.
Nicolas.

**Comment by nels0nwu** [comment]
Thank you Nicolas, this is really cool!

I try to review the translations even when I can't speak the languages.
I believe `et demi` should be `et demie`. I'm not sure about the use of `pile` as it would display for 5 minutes. Would `heures` be a better match? What do you think @nikogrnr

**Comment by nikogrnr** [comment]
Hi,
You're right, its `et demie`
`pile` has the same signification that `O clock`, but it's much better that you'll use `heures` for the five first minutes

**Comment by nels0nwu** [comment]
Merged and released 🚀
